### ISSUE TITLE
Not working in IE8

### ISSUE THREAD

**Issue by ramansharma89** [hernansartorio/jquery-nice-select#1]
Is it possible to make it work in IE 8? Basic functionality at least.

Regards,
Raman

**Comment by hernansartorio** [comment]
Hi Raman! Thanks for pointing that out. I stopped developing with support for IE8 some time ago (now I just put a conditional banner recommending a more modern browser), so I didn't even check if it worked with it.

I might take a look when I have the time, but please feel free to investigate the issue yourself and make a pull request if you can fix it! A wild guess is that it might have something to do with unsupported CSS properties used to hide/display the options.

Best,
Hernán

**Comment by BB-000** [comment]
Hi guys, did anyone work this one out?

**Comment by BB-000** [comment]
@hernansartorio  Yup you were right :]  ie8 didn't like the opacity on the .list, .list.open  

I changed it to use display: none & block instead in < ie9

**Comment by hernansartorio** [comment]
@BB-000 Awesome, thanks for finding that out! What approach did you use to apply that CSS for <IE9?

**Comment by hernansartorio** [comment]
FIxed with e3798e7.
