### ISSUE TITLE
Up/down arrow not rendered correctly in IE9.

### ISSUE THREAD

**Issue by hifall** [hernansartorio/jquery-nice-select#10]
Instead of rendered as arrows, it looks like this:

<img width="119" alt="screen shot 2016-02-12 at 9 08 09 pm" src="https://cloud.githubusercontent.com/assets/5734293/13007658/c6be9136-d1cc-11e5-8fc9-116aae785c1c.png">

BTW, it's an awesome plugin! Light-weight, slick, and works almost anywhere!

Would be great if the IE9 arrow issue can be fixed.

**Comment by hernansartorio** [comment]
Thanks for noticing that and for your comments! Just fixed it with e3798e7.
