### ISSUE TITLE
Overflow problem

### ISSUE THREAD

**Issue by Hazarapet** [hernansartorio/jquery-nice-select#15]
![rsz_settings-date](https://cloud.githubusercontent.com/assets/4758675/13323457/9db1eaae-dbea-11e5-9bc1-b35ca9fcb74b.jpg)
 I can't set a style to solve this.Any ideas?

**Comment by hernansartorio** [comment]
Looks like you have a max-height applied on the `.list` element, is that intentional?

**Comment by Hazarapet** [comment]
I have height yes.I need it that's why I put that style on .list

**Comment by hernansartorio** [comment]
For the scrollbar? Did you add a `overflow: scroll` too? What browser are you on?

**Comment by Hazarapet** [comment]
Chrome. I have overflow: auto
(by the way.Can you set a version for bower please.? "bower info" gives me nothing about version)

**Comment by hernansartorio** [comment]
I can't tell without looking at an example, but I just tried with `overflow: scroll; max-height: 200px;` and it works great.

Bower version, it was just added actually: #14 .

**Comment by Hazarapet** [comment]
Thanks for bower

**Comment by Hazarapet** [comment]
I'm sorry but your solution didn't work.I don't think this issue is closed.
