### ISSUE TITLE
Multiple select

### ISSUE THREAD

**Issue by BrunoViera** [hernansartorio/jquery-nice-select#2]
Hello Herman, really nice work! I have a doubt, you will have support for multiple select?? that will be really  awesome!

Regards

**Comment by hernansartorio** [comment]
Thanks Bruno! Honestly I don't plan to support multiple selects, mainly because they don't seem like a very good pattern to me from a UX perspective, and even less on a dropdown.

Saludos!

**Comment by BrunoViera** [comment]
Hello, thanks for your quick answer!
