### ISSUE TITLE
not work on ajax requests

### ISSUE THREAD

**Issue by amin101** [hernansartorio/jquery-nice-select#21]
Thanks for great plugin. when a page is loaded via Ajax the select elements doesn't turn to nice select .it seems `niceSelect()` function does not work on ajax loaded pages

**Comment by hernansartorio** [comment]
`niceSelect()` needs to be called on existing `select` elements, therefore you should call it after the ajax call is done.

**Comment by AstghikMirijanyan** [comment]
> `niceSelect()` needs to be called on existing `select` elements, therefore you should call it after the ajax call is done.

and how do you imagine it

**Comment by AstghikMirijanyan** [comment]
> `niceSelect()` needs to be called on existing `select` elements, therefore you should call it after the ajax call is done.

as standard select nice select does not open up
