### ISSUE TITLE
How to disable nice-select on click event of other check box

### ISSUE THREAD

**Issue by nileshyadav326** [hernansartorio/jquery-nice-select#3]
Hi I have to disable my dropdown on click of checkbox how to implement the same in nice select

**Comment by hernansartorio** [comment]
Hi Nilesh, sorry for the delay! Thank you pointing that out, it's certainly a common use case and something I planned to add. I'll try too add that functionality later this week.

**Comment by hernansartorio** [comment]
Sorry for the big delay. You can now do:

```javascript
$('#some-select').prop('disabled', true).niceSelect('update');
```

**Comment by Harrrrry** [comment]
Hi, Can i remove nice select for some select box, is there any way to do like this.

**Comment by sivapc** [comment]
@Harrrrry  : you can do this

  $(document).ready(function() {
      $('select:not(.ignore)').niceSelect();      
      FastClick.attach(document.body);
    });  

And add class 'ignore' to select element as below
<select  class="ignore" name="tshirt_size" >
