### ISSUE TITLE
Inconsistent license problem on cdnjs

### ISSUE THREAD

**Issue by hare1039** [hernansartorio/jquery-nice-select#37]
Hi, I am a contributor from cdnjs. We would like to host this library on our server, but we can't host it without a consistent license. Would you please confirm which license this library used. Thank you.
- MIT license from `bower.json`
- ISC license from `package.json`

issues on cdnjs
cdnjs/cdnjs/issues/9592
cdnjs/cdnjs/pull/10330

**Comment by hernansartorio** [comment]
Hi, the license should be MIT, will fix it when I have some time, or you can create a PR if you'd like.

**Comment by hare1039** [comment]
@hernansartorio Great! Thank you for your fast reply!
