### ISSUE TITLE
Deny selecting of disabled elements

### ISSUE THREAD

**Issue by pinguinjkeke** [hernansartorio/jquery-nice-select#5]
Firstly, I'm using this cool plugin in most of my projects. Thank you a lot for it!

It would be great to make disabled select elements grey or something.

I think I could try to implement it by myself. I can create a pull-request with my changes. Is it interesting for you? It would be really nice for me to participate

**Comment by hernansartorio** [comment]
Thanks Alexander!

It does have a disabled state, the only problem is that for now it's only triggered when the select element is disabled before the plugin is initialized. I guess you're disabling them dynamically right?

Of course, any contribution is welcomed! How would you go about making this work?

**Comment by pinguinjkeke** [comment]
It has disabled state for whole selectbox, not for options. Am I right?

On first attempt of implementation I have faced with a problem: event I created on selectbox fires before another event in my code and causes a logic error.
So I think about a .delay(10).queue(function() {});

In other word, the problem is events priority. Have you any ideas about it?

**Comment by hernansartorio** [comment]
Hey, sorry for the delay!

I thought you meant a disabled state for the whole dropdown, adding it for an option doesn't need much code or any new events, it's the same logic used for setting the selected option. 

I just pushed a commit for it: a240dba45507af48b9f1331f409c0d730515fb30
