### ISSUE TITLE
Scroll on specific height.

### ISSUE THREAD

**Issue by ghost** [hernansartorio/jquery-nice-select#65]
There is no scroll inside nice-select. On overflow scroll bar appears in body.

**Comment by samirmammadhasanov** [comment]
Change .list class like this: 
`.list { \n`
`}`

**Comment by samirmammadhasanov** [comment]
Thange .list class like this:

```
.list {
      opacity: 1;
      pointer-events: auto;
      -webkit-transform: scale(1) translateY(0);
          -ms-transform: scale(1) translateY(0);
              transform: scale(1) translateY(0);
      // for overflow. from here.
      height: 60vh;
      overflow: auto;
    }
```

**Comment by samirmammadhasanov** [comment]
Change .list class like this:

```
.list {
      opacity: 1;
      pointer-events: auto;
      -webkit-transform: scale(1) translateY(0);
          -ms-transform: scale(1) translateY(0);
              transform: scale(1) translateY(0);
      // for overflow. from here.
      height: 60vh;
      overflow: auto;
    }
```

**Comment by samirmammadhasanov** [comment]
Change .list class like this:

```
.list {
      opacity: 1;
      pointer-events: auto;
      -webkit-transform: scale(1) translateY(0);
          -ms-transform: scale(1) translateY(0);
              transform: scale(1) translateY(0);
      // for overflow. from here.
      height: 60vh;
      overflow: auto;
    }
```

**Comment by samirmammadhasanov** [comment]
Change .list class like this:  (overflow fix + custom scroll bar)

// List and options
  .list {
    background-color: #fff;
    border-radius: $input_border_radius;
    box-shadow: 0 0 0 1px rgba($gray_dark, .11);
    box-sizing: border-box;
    margin-top: 4px;
    opacity: 0;
    padding: 0;
    pointer-events: none;
    position: absolute;
    top: 100%; left: 0;
    -webkit-transform-origin: 50% 0;
        -ms-transform-origin: 50% 0;
            transform-origin: 50% 0;
    -webkit-transform: scale(.75) translateY(- $input_height / 2);
        -ms-transform: scale(.75) translateY(- $input_height / 2);
            transform: scale(.75) translateY(- $input_height / 2);
    -webkit-transition  
: all .2s cubic-bezier(0.5, 0, 0, 1.25), opacity .15s ease-out;
    transition: all .2s cubic-bezier(0.5, 0, 0, 1.25), opacity .15s ease-out;
    z-index: 9;

    // for overflow. from here.
    height: 60vh;
    overflow: auto;

    // for custom scrollbar inside select box
    &::-webkit-scrollbar{
      width: 14px;
      height: 18px;
      //background
    }
    &::-webkit-scrollbar-thumb {
      height: 6px;
      border: 4px solid rgba(0, 0, 0, 0);
      background-clip: padding-box;
      -webkit-border-radius: 7px;
      background-color: rgba(0, 0, 0, 0.15);
      -webkit-box-shadow: inset -1px -1px 0px rgba(0, 0, 0, 0.05), inset 1px 1px 0px rgba(0, 0, 0, 0.05);
      //cubug
    }
    &::-webkit-scrollbar-button {
      width: 0;
      height: 0;
      display: none;
    }
    &::-webkit-scrollbar-corner {
      background-color: transparent
    }
    &:hover .option:not(:hover) {
      background-color: transparent !important;
    }
  }

**Comment by samirmammadhasanov** [comment]
Change .list class like this:  (overflow fix + custom scroll bar)

// List and options
  .list {
    background-color: #fff;
    border-radius: $input_border_radius;
    box-shadow: 0 0 0 1px rgba($gray_dark, .11);
    box-sizing: border-box;
    margin-top: 4px;
    opacity: 0;
    padding: 0;
    pointer-events: none;
    position: absolute;
    top: 100%; left: 0;
    -webkit-transform-origin: 50% 0;
        -ms-transform-origin: 50% 0;
            transform-origin: 50% 0;
    -webkit-transform: scale(.75) translateY(- $input_height / 2);
        -ms-transform: scale(.75) translateY(- $input_height / 2);
            transform: scale(.75) translateY(- $input_height / 2);
    -webkit-transition  
: all .2s cubic-bezier(0.5, 0, 0, 1.25), opacity .15s ease-out;
    transition: all .2s cubic-bezier(0.5, 0, 0, 1.25), opacity .15s ease-out;
    z-index: 9;
    // for overflow. from here.
    height: 60vh;
    overflow: auto;
    // for custom scrollbar inside select box
    &::-webkit-scrollbar{
      width: 14px;
      height: 18px;
    }
    &::-webkit-scrollbar-thumb {
      height: 6px;
      border: 4px solid rgba(0, 0, 0, 0);
      background-clip: padding-box;
      -webkit-border-radius: 7px;
      background-color: rgba(0, 0, 0, 0.15);
      -webkit-box-shadow: inset -1px -1px 0px rgba(0, 0, 0, 0.05), inset 1px 1px 0px rgba(0, 0, 0, 0.05);
    }
    &::-webkit-scrollbar-button {
      width: 0;
      height: 0;
      display: none;
    }
    &::-webkit-scrollbar-corner {
      background-color: transparent
    }
    &:hover .option:not(:hover) {
      background-color: transparent !important;
    }
  }

**Comment by ghost** [comment]
Change .list class like this:  (overflow fix + custom scroll bar)

```
// List and options
  .list {
    background-color: #fff;
    border-radius: $input_border_radius;
    box-shadow: 0 0 0 1px rgba($gray_dark, .11);
    box-sizing: border-box;
    margin-top: 4px;
    opacity: 0;
    padding: 0;
    pointer-events: none;
    position: absolute;
    top: 100%; left: 0;
    -webkit-transform-origin: 50% 0;
        -ms-transform-origin: 50% 0;
            transform-origin: 50% 0;
    -webkit-transform: scale(.75) translateY(- $input_height / 2);
        -ms-transform: scale(.75) translateY(- $input_height / 2);
            transform: scale(.75) translateY(- $input_height / 2);
    -webkit-transition  
: all .2s cubic-bezier(0.5, 0, 0, 1.25), opacity .15s ease-out;
    transition: all .2s cubic-bezier(0.5, 0, 0, 1.25), opacity .15s ease-out;
    z-index: 9;
    // for overflow. from here.
    height: 60vh;
    overflow: auto;
    // for custom scrollbar inside select box
    &::-webkit-scrollbar{
      width: 14px;
      height: 18px;
    }
    &::-webkit-scrollbar-thumb {
      height: 6px;
      border: 4px solid rgba(0, 0, 0, 0);
      background-clip: padding-box;
      -webkit-border-radius: 7px;
      background-color: rgba(0, 0, 0, 0.15);
      -webkit-box-shadow: inset -1px -1px 0px rgba(0, 0, 0, 0.05), inset 1px 1px 0px rgba(0, 0, 0, 0.05);
    }
    &::-webkit-scrollbar-button {
      width: 0;
      height: 0;
      display: none;
    }
    &::-webkit-scrollbar-corner {
      background-color: transparent
    }
    &:hover .option:not(:hover) {
      background-color: transparent !important;
    }
  }
```
