### ISSUE TITLE
setting selected does not update on screen

### ISSUE THREAD

**Issue by noomnahor** [hernansartorio/jquery-nice-select#7]
Using:
```javascript
$("#selectorTest").val(value);
```
On a `<select>` element does not update the currently selected option.

Using
```javascript
console.log($("#selectorTest").val())
```
Logs the expected value.

Refreshing the page will update the `<select>` to the set option.

Standard `<select>` elements will update their selected option immediately when using jQuery.val()

**Comment by hernansartorio** [comment]
Hi, sorry for the delay. You can now do:

```javascript
$("#selectorTest").val(value).niceSelect('update');
```
