### ISSUE TITLE
not working with dynamic multiple select element

### ISSUE THREAD

**Issue by dhullsumit** [hernansartorio/jquery-nice-select#71]
I am working with a multiple select element. where second element is build when first have some change. value is changed but nice select not working with newly build select element. 
Please give a solution ASAP.

Thank-you  in advance :)

**Comment by Yooun** [comment]
Any update on this issue ? I'm facing the same problem when "chaining"  select elements.

**Comment by dhullsumit** [comment]
@Yooun  yes, you may trigger niceselect function on change of first element
