### ISSUE TITLE
Disabled not working properly

### ISSUE THREAD

**Issue by Stiropor** [hernansartorio/jquery-nice-select#9]
There is a tiny bug in code, line 14:
```javascript
(select.attr('disabled') ? 'disabled' : '" tabindex="0') +
```
it should be:
```javascript
(select.attr('disabled') ? ' disabled' : '" tabindex="0') +
```
A space is needed before 'disabled' (same as before tabindex), currently it appends 'disabled' to last class name and it's not working right.

**Comment by hernansartorio** [comment]
Sorry, I changed that code a bit on a previous commit and didn't realize about that, just fixed it. Thanks for pointing it out!
